// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Neon.Payment;
using System;

namespace Neon.Payment.Migrations
{
    [DbContext(typeof(PaymentContext))]
    partial class PaymentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Neon.Payment.Models.TaOrders", b =>
                {
                    b.Property<int>("OrdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ORD_ID");

                    b.Property<decimal>("OrdCost")
                        .HasColumnName("ORD_COST")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<int>("OrdUserId")
                        .HasColumnName("ORD_USER_ID");

                    b.Property<DateTime?>("RegDt")
                        .HasColumnName("REG_DT")
                        .HasColumnType("datetime");

                    b.Property<string>("RegId")
                        .HasColumnName("REG_ID")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("RegIp")
                        .HasColumnName("REG_IP")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("OrdId");

                    b.ToTable("TA_ORDERS");
                });
#pragma warning restore 612, 618
        }
    }
}
