// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NeonCore;
using System;

namespace NeonCore.Migrations
{
    [DbContext(typeof(JWDBContext))]
    partial class JWDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NeonCore.Models.ChangeLog", b =>
                {
                    b.Property<int>("ChangeLogId")
                        .HasColumnName("ChangeLogID");

                    b.Property<DateTime?>("ChangeDtm")
                        .HasColumnType("datetime");

                    b.Property<string>("ClassNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CurrentValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("PropertyNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserNm")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("ChangeLogId");

                    b.ToTable("ChangeLog");
                });

            modelBuilder.Entity("NeonCore.Models.TaUser", b =>
                {
                    b.Property<int>("UserIdx")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("USER_IDX");

                    b.Property<string>("Addr1")
                        .IsRequired()
                        .HasColumnName("ADDR1")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Addr2")
                        .IsRequired()
                        .HasColumnName("ADDR2")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Hp")
                        .IsRequired()
                        .HasColumnName("HP")
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnName("PWD")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("REG_ID")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RegIp")
                        .IsRequired()
                        .HasColumnName("REG_IP")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnName("TEL")
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnName("USER_ID")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("UserNm")
                        .IsRequired()
                        .HasColumnName("USER_NM")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("UserIdx");

                    b.ToTable("TA_USER");
                });
#pragma warning restore 612, 618
        }
    }
}
